- hosts: localhost
  roles:
    - role: emit-job-header

- hosts: all
  #gather_facts: true
  roles:
    - validate-host
    - add-build-sshkey
    - start-zuul-console
    - log-inventory
    - prepare-workspace
    - mirror-info

